### PR TITLE
Admin dashboard UI issues fixed

### LINKED ISSUE #369: [Dev] Admin Dashboard : Fix UI issues
1. Update the margin around the 2 graphs
2. Leave a space between the 2 graphs

Image

{Refer the Figma Design [Admin Panel]  v1.0.2-qa2 : https://www.figma.com/design/B0M4LvASkmA1MCM1v2JFUa/Hospitality-Management-System?node-id=0-1&t=X5PNQ3IglYFltzxS-1 }

### LINKED ISSUE #371: [Dev] Admin Rooms : Fix UI issues
1. Room details text should be align to the other boxes.

Image

2. Put Title, Subtitle, Description title and Description in a box.

Image

3. [Image Upload Submit Button] Corner Radius should be in 8
4. [Image Upload Submit Button]Hover should be in #192959
5. [Image Upload Submit Button]Text should be in "Submit"
6. Gallery Text should be placed outside of the box

Image

7. Additional information title placeholder should be corrected as "Enter Additional Information Title"
8. Additional information title should be in BOLD
9. Additional Information Description should be BOLD

Image

10. Remove the Enter category name  text field under category title

(implemented view) :- 
Image

(UI Design) :- 
Image

11. Towels placeholder text should be update for the "Tags"

Image

12. Close Button Outline colour should be in #5B5959
13. Close Button Hover should be in #192959
14. Close Button text should be in "Close"
15. Save Button Hover should be in #192959
16. Save Button text should be in "Save"

Image

17. Margin should be add to the bottom of the page

Image

{Refer the Figma Design [Admin Panel]  v1.0.2-qa2 : https://www.figma.com/design/B0M4LvASkmA1MCM1v2JFUa/Hospitality-Management-System?node-id=0-1&t=X5PNQ3IglYFltzxS-1 }

### PR DESCRIPTION
**Pull request by Kasunkule**
Update the margin around the 2 graphs and Leave a space between the 2 graphs fixed

### CODE REVIEW

**Review by iamarasekera — CHANGES_REQUESTED** [review]
Renames to file to tsx format,

File: app/admin/room-details/page.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ const roomDetails = () => {
   return (
     <>
       <Box
-        sx={{ backgroundColor: "#EEF5FF", padding: "10px 0", width: "100%" }}
+        sx={{ backgroundColor: "#EEF5FF", padding: "10px 0", width: "100%", marginLeft: "17px"}}
```
Comment (iamarasekera) [inline app/admin/room-details/page.tsx]: Please use 
mx | margin-left as per the MUI documentation
https://mui.com/system/spacing/




</body>
</html>

**Review by iamarasekera — APPROVED** [review]
