### PR TITLE
Fixed feature contact us

### LINKED ISSUE #314: [Dev] Update The Contact Us Page UI  As per the Design
Update The Contact Us Page UI  As per the Design

Image

Prototype :https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=x09WYMApifmq4qad-0

### PR DESCRIPTION
**Pull request by BupendraDhyan**

### CODE REVIEW

File: components/contactPage/HeaderSection.tsx [hunk 1]
```diff
@@ -17,6 +17,7 @@ const HeaderSection = () => {
           <Box
             sx={{
               paddingTop: { xs: "25px", sm: "50px", md: "50px" },
```
Comment (iamarasekera) [inline components/contactPage/HeaderSection.tsx:19]: Try to use MUI spacing or padding and margin
https://mui.com/system/spacing/

**Review by iamarasekera — APPROVED** [review]
