### PR TITLE
Multiple UI issues across admin pages

### LINKED ISSUE #575: [Bug] Multiple UI Issues Across Admin Pages
Description:
There are multiple UI issues across the Admin Rooms Page, Admin Rooms Details Page , Admin Blog Page, Admin Contact Us Page, and Admin Content pages.
Admin Room Details Page - incorrect placeholders, missing bold text, visibility problems with checkbox selections
Admin Rooms Page - improperly sized and misaligned buttons(close & save buttons)
Admin Blog Page - improperly sized and misaligned buttons(Save Draft Button & publish Button )
Admin Contact Us Page - improperly sized and misaligned buttons (view & submit buttons)
Admin Content pages -  mismatched button hover colors

Steps to Reproduce:

Admin Rooms Page
1.Navigate to the Admin Rooms Page.
2..Observe the sizes and alignment of the Save & Close buttons.

Admin Rooms Details Page
1.Navigate to the Admin Rooms Page.
2.Observe the placeholder for the Additional Information title.
3.Check the Additional Information Description text.
4.Check the alignment of the cover image submit button.
5.Select items in the Add-ons section and observe the checkbox selections visibility.(both web and mobile view)
6.In the gallery image box, observe the "uploading symbol" is overlapped with the text (“Drag & Drop Your images or Browse”) in the mobile view.
7..Observe the sizes and alignment of the Save & Close buttons.

Admin Blog Page
1.Navigate to the Admin Blog Page.
2.Observe the sizes of the Save Draft and Publish buttons.
3.Check the color of the Publish button.

Admin Contact Us Page
1.Navigate to the Admin Contact Us Page.
2.Observe the size of the Submit button.

Admin Content Page
1.Navigate to all admin content pages.
2.Hover over buttons and observe the hover colors.

Expected Result:

Admin Rooms
- The Save & Close buttons should be resized and aligned to the right as per the figma design.

Admin Rooms Details Page
- The placeholder for the Additional Information title should be "Enter Additional Information".
- The Additional Information Description should be bold.
- The Save & Close buttons should be resized and aligned to the right as per the design.
- The cover image submit button should be centered within the box.
- Checkbox selections in the Add-ons section should be visibly reflected.
- In mobile view, the uploading symbol in the gallery image box should not overlap with the text.

Admin Blog Page
- The Save Draft and Publish buttons should be resized as per the figma design.
- The color of the Publish button should match the figma design.

Admin Contact Us Page
- The Submit button should be resized as per the design.

Admin Content All Pages
- Button hover colors should match the design.

Actual Result:

Admin Rooms Page
- The Save & Close buttons are not properly resized or aligned.

Admin Rooms Details Page
- The placeholder for the Additional Information title is incorrect.
- The Additional Information Description is not bold.
- The Save & Close buttons are not properly resized or aligned.
- The cover image submit button is not centered.
- Checkbox selections in the Add-ons section are not visible.
- In mobile view, the "uploading symbol" overlaps with the text in the gallery image box.

Admin Blog Page
- The Save Draft and Publish buttons are not properly resized.
- The Publish button color is incorrect.

Admin Contact Us Page
- The Submit button is not properly resized.

Admin Content All Pages
- Button hover colors do not match the design.

### PR DESCRIPTION
**Pull request by wickramasinghe07**

### CODE REVIEW

File: app/admin/rooms/page.tsx [hunk 1]
```diff
@@ -311,30 +311,30 @@ const Rooms = () => {
...
-                <Button
-                  variant="contained"
-                  sx={{
-                    borderColor: "#5B5959", // Set outline color
-                    "&:hover": {
-                      backgroundColor: "#192959", // Set hover background color
-                    },
-                  }}
-                >
-                  Close
```
Comment (iamarasekera) [inline app/admin/rooms/page.tsx:324]: Please update only the necessary changes.

File: app/admin/rooms/page.tsx [hunk 2]
```diff
@@ -360,34 +361,34 @@ const Rooms = () => {
...
-                </Button>
-                <Button
-                  variant="outlined"
-                  sx={{
-                    borderColor: "#5B5959", // Set outline color
-                    "&:hover": {
-                      backgroundColor: "#192959", // Set hover background color
-                    },
```
Comment (iamarasekera) [inline app/admin/rooms/page.tsx:381]: Please update only the changes. Please don't remove chunks of code and readd.

**Review by iamarasekera — APPROVED** [review]
